# Generated by Django 5.1.6 on 2025-02-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_sport_type_profile_cardio_type_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Weight', models.IntegerField(max_length=2)),
                ('num_sets', models.IntegerField()),
                ('num_reps', models.IntegerField()),
                ('Muscle', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Arm', 'Arm'), ('Leg', 'Leg')], max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='Cardio_type',
            field=models.CharField(choices=[('Trademill', 'Trademill'), ('stairmaster', 'Stairmaster'), ('boxing', 'Boxing'), ('swimming', 'Swimming')], max_length=12),
        ),
    ]
