# Generated by Django 5.1.5 on 2025-02-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Weight',
            field=models.FloatField(null=True),
        ),
    ]
