# Generated by Django 5.1.6 on 2025-02-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=10)),
                ('Birthday', models.DateField()),
                ('Age', models.FloatField(max_length=2)),
                ('Is_coach', models.BooleanField()),
                ('Weight', models.FloatField()),
                ('Height', models.FloatField()),
                ('Sport_type', models.CharField(choices=[('Trademill', 'Sport1'), ('stairmaster', 'Sport2'), ('boxing', 'Sport3'), ('swimming', 'Sport4')], max_length=12)),
            ],
        ),
    ]
