# Generated by Django 5.1.6 on 2025-02-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_profile_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='DateOfbirth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Age',
            field=models.IntegerField(),
        ),
    ]
