# Generated by Django 4.2.11 on 2025-04-09 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0027_alter_profile_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='num_reps',
            new_name='reps',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='num_sets',
            new_name='sets',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='Muscle',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.AddField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workout', models.CharField(choices=[('Push', 'Chest'), ('Back', 'Back'), ('Arm', 'Arm'), ('Leg', 'Leg')], max_length=6)),
                ('data', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
