# Generated by Django 5.1.6 on 2025-04-10 15:13

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_exercise_workout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='Weight',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='workoutday',
            old_name='Workout',
            new_name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutday',
            name='data',
        ),
        migrations.AddField(
            model_name='exercise',
            name='persent_failure',
            field=models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='workoutday',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='workout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='api.workoutday'),
        ),
    ]
