# Generated by Django 5.1.6 on 2025-04-10 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_rename_weight_exercise_weight_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workout',
            new_name='Workout',
        ),
    ]
